[package]
name = "asyrmetry"
version = "0.1.0"
edition = "2021"

[dependencies]
dasp = { version = "^0.11" }
eyre = { version = "^0.6" }
symphonia = { version = "^0.5", features = ["mp3"] }
tinyaudio = { version = "^1.0" }

[profile.dev]
opt-level = 1
